/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package pro.ryutans;

public class App {
    public static void main(String[] args) {
        CharaSort sort = new CharaSort();
    }
}
